name: Deliver docker image

on:
  push:
    branches: [ master ]

jobs:
  push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: ./gradlew --console=plain shadowJar
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dripolles/project-k
          tags: latest
