name: Kotlin linting + static analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - run: chmod +x gradlew
      - run: ./gradlew --console=plain detekt
